import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthSession from "@/providers/AuthSession";
import ReduxClientProvider from "@/providers/ReduxProvider";
import Auth from "@/functions/Auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Photocess",
  description: "Generated by create next app",
  icons: {
    icon: "/navLogo.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxClientProvider>
          <AuthSession>
            {children}
            <Auth />
          </AuthSession>
        </ReduxClientProvider>
      </body>
    </html>
  );
}
